# Debug
s74q_t_q_o_q8: true
# Whether to open a card for Class-D personnel at the beginning
u_jir5yv_d7: true
# What card is given to Level D personnel?
afx7klcnq: KeycardJanitor
# randomly brush the electromagnetic gun on the nine-tailed commander
arcd_tv_a_h_d: true
# Whether to open the service welcome
jk_x01pmfc: true
# Welcome message when players enter the server
uc_l8_d0u_dg: Welcome% playername%~
# Welcome message display duration
o_ock_q_pe0_p: 5
# Open round end message
g_z_lxuhi_s_i: true
# round end message
eeo6l_iu_p_z: The round is over! Don't leave, see you in the next game.
# infinite ammo
dvhj_h4_v0s: true
# Enable modifying SCP blood volume system
pcx_lj4mv_f: true
# SCP173, SCP939, SCP049, SCP049-2, SCP096, SCP106 blood volume
r_u_j4_v3a_dh:
- 4000
- 2400
- 2000
- 400
- 2500
- 2000
# Clear the body
f_jghh3_qpc_p: true
# Enable. bc and. c chat system
d15hctvm3_z: true
# Enable player feedback management system
aj_rhf2o_tj4: true
# Enable player self-rescue system
r_g_kh_psbx_no: false
# How long will a person's chat information be displayed/s
iu_oh_kpgg_s_j: 4
# Enable lazy person system
e_i1hp_s_n_a_so: true
# Valid for doors of SCP
v_oih_gg98l1: true
# also valid for cabinet
g_c_yh_r_lmb7l: true
# also valid for electric board
k_z_zhv_y_twd_w: true
# If the player doesn't work in the dog's fart
o_n4hww9_c67: true
# Please open this system if it doesn't work
i8_vh_cip_t_w_g: true
# Valid for normal door
m3_ah_sj_i2n_d: true
# SCP-703
do_vhn_pf6kg: true
# How often to give 703 items
iu_gh_v_e_y_me_g: 4
# SCP-029
d6_zh5_k_mj2v: true
# Chaos Leader
e_r_dho_j8bee: true
# Enable the changeable security team
ls_lh9ef_jkt: true
# Enable server scheduled broadcast
bo_ihabxi_h_h: true
# How often does the server broadcast regularly
au9h_iqlwl_p: 5
# How long will the server display the scheduled broadcast
gh4hb_cgk_tn: 5
# Server Broadcast Text
mrxhz37hc_r: Server Broadcast
