# Debug
tre5m_y1x6: true
# Whether to give a card for Class-D personnel at the beginning of the round
j_ud_wv2_s_xj: true
# What card is given to Level D personnel?
y1_c_s_s4i_x_m: KeycardJanitor
# randomly brush the electromagnetic gun on the nine-tailed commander
v_q_g_r_s_n_gu_o: true
# Whether to open the service welcome
o_u_aqx_md_dj: true
# Welcome message when players enter the server
d8jm_m_s_o5_k: Welcome% playername%~
# Welcome message display duration
d5_edox_ecl: 5
# Open round end message
h_n_p_m_bx_cvv: true
# round end message
yhhk_u_j_big: The round is over! Don't leave, see you in the next game.
# infinite ammo
o_a_c_jy_p6_b4: true
# Enable modifying SCP blood volume system
x_ul8kkm_t_m: true
# SCP173, SCP939, SCP049, SCP049-2, SCP096, SCP106 blood volume
av_as_f1_df_m:
- 4000
- 2400
- 2000
- 400
- 2500
- 2000
# Clear the body
q_f_i4424x2d: true
# Enable. bc and. c chat system
y_sq4_q_jtybv: true
# Enable player feedback management system
ce_y4c_l_g_y_l9: true
# Enable player self-rescue system
s_xn4ou_w_cm_h: 4
# Enable lazy person system
hw_k4_zbv_z_pj: true
# Valid for doors of SCP
p_q_r4_ty2j_d_c: true
# also valid for cabinet
ywa46i0k_xq: true
# also valid for electric board
d_m64_p_w_x_wfm: true
# If the player doesn't work in the dog's fart
o024hnm2k_k: true
# Please open this system if it doesn't work
kp642_e_pc9_i: true
# Valid for normal door
ao_a4w_um_wqu: true
# SCP-703
kr_b4yc9_m3d: true
# How often to give 703 items
dik47_bhs_y_d: 4
# SCP-029
pj_f4_k_y_ec6_w: true
# Chaos Leader
r_j_q4_d_bg_w67: true
# Enable the changeable security team
s4_m4_i_z_a6j_q: true
# Enable server scheduled broadcast
g3_f4_l_ih_lu_j: true
# How often does the server broadcast regularly
d_lx4_a6_lx_v6: 5
# How long will the server display the scheduled broadcast
l_ba4n_s7_g9b: 5
# Server Broadcast Text
b3_w4uni_i_j_x: Server Broadcast
